development:
  secret_key_base: sk_test_oqLhQtgubLLEA1x7AhxajOFc00nUVLyEaG

  # stripeのキーの実装
  stripe_publishable_key: pk_test_XQHhn69wVifJq9c2QVz5vKgU00SbymLYAl
  stripe_secret_key: sk_test_oqLhQtgubLLEA1x7AhxajOFc00nUVLyEaG

test:
  secret_key_base: sk_test_oqLhQtgubLLEA1x7AhxajOFc00nUVLyEaG